use_frameworks!

platform :ios, '10.0'

target 'FPThemeKit_Example' do
  pod 'FPThemeKit', :path => '../'

  target 'FPThemeKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
  
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
  end
end
